apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app               # Name of your Argo CD Application
  namespace: kube-system   # Namespace where the Application is deployed (optional)
spec:
  destination:
    server: https://kubernetes.default.svc  # Kubernetes cluster API server URL
    namespace: kube-system          # Target namespace for your application
  project: default                       # Project (optional)
  source:
    repoURL: https://github.com/sharminaka/ecommerce.git  # Git repository URL
    path: /k8s                 # Path within the Git repository
    targetRevision: main                   # Git branch or commit hash
  syncPolicy:
    automated:
      prune: true                           # Prune resources not defined in the manifests
    syncOptions:
    - CreateNamespace=true                  # Create the target namespace if it doesn't exist
